In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
### Generate some nice data
### rotating about x and y axis

import numpy as np
from rotation_helpers import xyz_to_rotation

rest_pt = np.array([0.1, 0.2, 0.3])
pt = np.array([0., 0., 0.5])

Tmats = []

for x_rot in np.linspace(-0.3,0.3,5):
    for y_rot in np.linspace(-0.3,0.3,5):
        rotation = np.array([x_rot, y_rot, 0])
        new_rotmat = xyz_to_rotation(rotation)
        new_pt = new_rotmat@pt+rest_pt
        Tmat = np.eye(4)
        Tmat[:3,3] = np.squeeze(new_pt)
        Tmat[:3,:3] = new_rotmat
        Tmats.append(Tmat)
        
print(Tmats[3])
#print(Tmats[15])

[[ 9.88771078e-01 -4.41619878e-02  1.42763701e-01  1.71381850e-01]
 [-3.46944695e-18  9.55336489e-01  2.95520207e-01  3.47760103e-01]
 [-1.49438132e-01 -2.92201833e-01  9.44609090e-01  7.72304545e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [3]:
from constraint import PointConstraint
constraint = PointConstraint()
constraint.fit(Tmats)

ModuleNotFoundError: No module named 'decision_vars'